name: Deploy
on:
  worflow_call:
    inputs:
      working-directory:
        type: string
        default: .
    secrets:
      vercel-token:
        required: true
        type: string
      github-token:
        required: true
        type: string
      vercel-org-id:
        required: true
        type: string
      vercel-project-id:
        required: true
        type: string
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.vercel-token }}
          github-token: ${{ secrets.github-token }}
          vercel-org-id: ${{ secrets.vercel-org-id }}
          vercel-project-id: ${{ secrets.vercel-project-id }}
          working-directory: ${{ secrets.working-directory }}
