name: 'Validate PR title'

on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true
      
jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            feat
            build
            chore
            ci
            docs
            style
            refactor
            perf
            test
          requireScope: false
          wip: true
          validateSingleCommit: false